using System.Diagnostics;
using System.IO;

namespace UFW_NFO
{
    public class Squirell
    {
        public static void RemoveHeadersWithSquirrel(NSPModel itemToProcess)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            var outDir = "\"" + itemToProcess.Name + itemToProcess.Version + "\"";
            var path = "\"" + itemToProcess.Path + "\"";
            var arguments = $"-o ./{outDir} --erase_deltas {path}";
            Process p = new Process();
            start.FileName = "./squirrel.exe";
            start.Arguments = arguments;
            //start.Arguments = string.Format("\"{0}\" \"{1}\"", "./squirrel.py", arguments);
            start.UseShellExecute = false; // Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true; // Any output, generated by application will be redirected back
            start.RedirectStandardError = true;

            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    process.WaitForExit();
                }
            }
        }
    }
}